### ISSUE TITLE
Don't use game code embedded in the source code

### ISSUE THREAD

**Issue by Swizzlefowl** [Swizzlefowl/Non-gamer-princess-alliance-exclusive-non-compliant-NES-Emulator-TODO-#1]
We shouldn't need to do this anymore after we have figured out how to parse nes format.

**Comment by IvarWithoutBones** [comment]
I urge you to consider if this is a real world issue effecting real world applications. My belief is that by embedding the binary directly inside of our executable we can show the end users a batteries-included experience, and are able to graciously achieve the real-time performance constraints inflicted upon us. The developer experience is hereby elevated to the next level, i suggest renaming our `main` branch to `ppu1` to reflect that. Please consider these factors prior to opening your next issue.

**Comment by Swizzlefowl** [comment]
I may have to admit that you have point, maybe other emu devs will start to harcode game binaries inside their emulators too.
