### ISSUE TITLE
it doesnt work on fedora os

### ISSUE THREAD

**Issue by EZonTheEyes** [Swizzlefowl/Non-gamer-princess-alliance-exclusive-non-compliant-NES-Emulator-TODO-#2]
please help me a man has kidnapped my child and he said i wont see her again unless i can speedrun metroid on nes fast enough to see swimsuit samus, i cant get this emulator to launch of my fedora:tm: os operating system
the clock is running and i have 2 hours and 46 minutes left to complete metroid or i wont be able to see my daughter again please help m

**Comment by Swizzlefowl** [comment]
I tip my hat to to the close button.

**Comment by EZonTheEyes** [comment]
my daughter is gone
